sudo: required

# Keep the sliding forward of the ci branch from triggering another build:
branches:
  except:
    - ci

# We don't use these facilities, but they're lightweight:
language: C

services:
  - docker

before_install:
  # Normalize ownership UIDs between host and container so container can write:
  - sudo chown -R 1000 .
  - make docker_es

script:
  - docker-compose -f tooling/docker/docker-compose.yml run -e DXR_PROD=1 dev make test

notifications:
  email: false
  irc:
    channels:
      - "irc.mozilla.org#static"
    template:
      - "[%{repository_name} %{branch} %{result}] \"%{commit_subject}\" by %{author}"
      - "Changes: %{compare_url}"
      - "Build details: %{build_url}"

deploy:
  provider: script
  script: tooling/travis_passed.sh
  on:
    branch: master
  skip_cleanup: true

env:
  global:
    - GH_REF: github.com/mozilla/dxr.git
    - secure: "ZaFYROXPqDRTb9iPK196ar5rOHDIcOw7xD7kV0bbXMAaJZv7T7TmQQ9gRso/qwwAeOKO4IRi9iGRDQU5yqZ4hy6FbVXUV6AXI3QXbm0X+qd38kboXzwfbpwfRpZRj5CmzZ32wo3w4jtB7OSzX6OvP+7J5YHRoRwTj30JLhLrXfk="
    - secure: "O8n+VSEjws3YKrsaJmY32bYgzSstmiF6nyyuwQIodoNFoAes5XXAIj8xvrJE40Co7HK2JztKUzb0Hkx7cLMZOMeou/HT9N5O3ML15Ka9CWZ0gD8C0IlZvc8x1jbuB97uD9omID1d/HzIPABj2YZjgh5HdsIJnHXx1xnJ/xtuASI="
